### PR TITLE
arm64: config: laptops: Enable settings for Docker

### PR DESCRIPTION
**Pull request by jallum**
Docker provides a check-config script that will analyze your
kernel configuration and make various recommendations. That script
can be found here:

https://github.com/moby/moby/blob/master/contrib/check-config.sh

Signed-off-by: Jason Allum <jallum@gmail.com>

### CODE REVIEW

**Comment by lag-linaro** [comment]
I wouldn't spend too much time on `laptops_defconfig`.

It's a Ubuntu config that we're using it for testing.

If you require these configs I suggest you upstream them directly into Ubuntu and the other distros.

**Comment by jallum** [comment]
I see. I think I misunderstood, then. I thought the project was working towards a sensible set of configuration defaults for laptops.  The upstream defconfig is very server-oriented, what with raid (etc. etc.) options enabled that make sense in a server context, but less so for a laptop.  I don't know that they'd find this to be useful.

**Comment by jallum** [comment]
I've rebased this onto the latest kernel, for anyone that may be interested in running docker on their machines in the meantime.

**Comment by lag-linaro** [comment]
The current `defconfig` isn't specifically for servers.  In theory it's defconfigs done right, with only the minimum functionality built-in and and everything else built as modules.  Distros have an even more enabled set of default configs with almost everything built as modules.

Having a default config per platform, rather than a single generic one is only really useful for platforms which can't afford the extra space required for the larger binary and/or modules.  Even with < `ARMv8` we now have `multi_v4t_defconfig`, `multi_v5_defconfig` and `multi_v7_defconfig` which have become the defacto default configs for their associated platforms.

**Pull request merged**
